CREATE TABLE notifications_types(
	[type_identifier] [uniqueidentifier] NOT NULL,
	[description] [varchar](50) NOT NULL
PRIMARY KEY CLUSTERED 
(
	[type_identifier] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
CONSTRAINT [UC_notifications_types] UNIQUE NONCLUSTERED 
(
	[description] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

INSERT INTO notifications_types
SELECT NEWID(), 'NEW_FOLLOWER'
UNION ALL
SELECT NEWID(), 'NEW_COMMENT'
UNION ALL
SELECT NEWID(), 'NEW_LIKE'