
CREATE TABLE tweets_types(
	[type_identifier] [uniqueidentifier] NOT NULL,
	[description] [varchar](20) NOT NULL
PRIMARY KEY CLUSTERED 
(
	[type_identifier] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
CONSTRAINT [UC_in_caixa_mov] UNIQUE NONCLUSTERED 
(
	[description] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

INSERT INTO tweets_types
SELECT NEWID(), 'TWEET'
UNION ALL
SELECT NEWID(), 'RETWEET'
UNION ALL
SELECT NEWID(), 'COMMENT'